#!/usr/bin/env bash
#
# Regenerates the files that the CoMaps core needs and that CoMaps does not version, and stores them in
# native-comaps/generated/ (committed). MAINTAINER SCRIPT: needs network the first time (PyPI: protobuf 3.x for kothic)
# and jq. A normal build, and F-Droid's, does NOT run it: they use the committed copies through scripts/comaps-stage.sh.
#
# Run it whenever the third_party/comaps submodule is bumped (scripts/comaps-check-generated.sh fails otherwise) and
# commit the result.
#
# Usage: scripts/comaps-generate.sh [--comaps DIR]     (default: third_party/comaps)
# The generation runs inside DIR (it overwrites the generated files there), so use a scratch copy if DIR must stay
# untouched. SKIP_PYTHON_VENV=1 uses the system python3 (which must provide protobuf 3.x) instead of a venv.
set -euo pipefail

ROOT="$(cd "$(dirname "$0")/.." && pwd)"
C="$ROOT/third_party/comaps"
if [ "${1:-}" = "--comaps" ]; then C="$(cd "$2" && pwd)"; fi
OUT="$ROOT/native-comaps/generated"
cd "$C"

if [ -z "${SKIP_PYTHON_VENV:-}" ]; then
  # Local venv with protobuf 3.x (required by kothic).
  set +u
  source ./tools/unix/activate_venv.sh
  set -u
fi

echo "== json strings and categories"
./tools/unix/generate_json_strings.sh
./tools/unix/generate_categories.sh

echo "== desktop UI strings (libs/platform/localized_types_map.cpp)"
./tools/unix/generate_desktop_ui_strings.sh

# Feature type names ("Pharmacy" / "Farmacia") per language for the search results' category (CoMaps only generates English).
echo "== localized type names (um_localized_types.inc)"
python3 "$ROOT/scripts/gen-localized-types.py" --comaps "$C"

# The core sets Android's default style (default/light) with SetCurrentStyle and therefore loads
# drules_proto_default_light.bin; without it, CoMaps init fails (verified on the Pixel 8). It is generated BEFORE the
# vehicle style: each libkomwm rewrites classificator.txt/types.txt/visibility.txt and vehicle must come last, as in
# tools/unix/generate_drules.sh.
echo "== drules default/light (required by core startup)"
python3 tools/kothic/src/libkomwm.py --txt \
  -s data/styles/default/light/style.mapcss \
  -o data/drules_proto_default_light \
  -p data/styles/default/include/

# classificator.txt, types.txt, visibility.txt, colors.txt and patterns.txt come from compiling ONE style
# (the vehicle one, as generate_drules.sh does at the end: "produce same visibility.txt & classificator.txt").
echo "== classificator/types/visibility from the vehicle style"
python3 tools/kothic/src/libkomwm.py --txt \
  -s data/styles/vehicle/light/style.mapcss \
  -o data/drules_proto_vehicle_light \
  -p data/styles/vehicle/include/
python3 tools/python/transit/transit_colors_export.py data/colors.txt > /dev/null

echo "== copying to native-comaps/generated/"
rm -rf "$OUT"
mkdir -p "$OUT/data" "$OUT/platform"
for f in classificator.txt types.txt visibility.txt colors.txt patterns.txt categories.txt drules_proto_default_light.bin; do
  cp "data/$f" "$OUT/data/$f"
done
cp libs/platform/localized_types_map.cpp "$OUT/platform/localized_types_map.cpp"

# Manifest: the submodule commit the files were generated from + SHA-256 of every committed generated file.
# The pinned commit is read from the superproject index, so it also works in a worktree and without the checkout.
COMMIT="$(cd "$ROOT" && git ls-files -s third_party/comaps | awk '{print $2}')"
{
  echo "# Generated by scripts/comaps-generate.sh. Do not edit."
  echo "comaps-commit $COMMIT"
  (cd "$ROOT" && sha256sum native-comaps/generated/data/* native-comaps/generated/platform/* \
     native-comaps/src/main/cpp/generated/um_localized_types.inc)
} > "$OUT/MANIFEST"
echo "Done: $(du -sb "$OUT" | cut -f1) bytes in native-comaps/generated/"
