#!/usr/bin/env python3
"""Generates native-comaps/src/main/cpp/generated/um_localized_types.inc: the human-readable feature type names
("Pharmacy" / "Farmacia") of the CoMaps core, one table per language.

Source (CoMaps, already part of the build): third_party/comaps/iphone/Maps/LocalizedStrings/<lang>.lproj/LocalizableTypes.strings,
lines of the form `"type.amenity.pharmacy" = "Farmacia";`. CoMaps' own desktop generator only reads the English file, which is
why search results used to show English categories on a Spanish phone.

Usage: scripts/gen-localized-types.py [--langs en,es] [--comaps DIR] [-o FILE]
A language whose file is missing is skipped with a warning (the core then falls back to English).
"""
import argparse
import os
import re
import sys

LINE = re.compile(r'^"((?:[^"\\]|\\.)*)"\s*=\s*"((?:[^"\\]|\\.)*)"\s*;\s*$')
LANG = re.compile(r"^[a-zA-Z]{2,3}([-_][A-Za-z0-9]{2,8})?$")
ROOT = os.path.join(os.path.dirname(os.path.abspath(__file__)), "..")


def parse(text):
    """{key: raw C-escaped value} for every well-formed, non-empty entry; comments and blank lines are ignored."""
    out = {}
    for line in text.splitlines():
        m = LINE.match(line.strip())
        if m and m.group(2):
            out[m.group(1)] = m.group(2)
    return out


def render(tables):
    """C++ initializer for `std::map<std::string, std::map<std::string, std::string>>`; languages and keys sorted."""
    lines = ["// Generated by scripts/gen-localized-types.py from CoMaps' LocalizableTypes.strings. Do not edit.",
             "{"]
    for lang in sorted(tables):
        lines.append(f'  {{"{lang}", {{')
        for key in sorted(tables[lang]):
            lines.append(f'    {{"{key}", "{tables[lang][key]}"}},')
        lines.append("  }},")
    lines.append("}")
    return "\n".join(lines) + "\n"


def load(comaps_dir, langs, log=lambda m: None):
    tables = {}
    for lang in langs:
        if not LANG.match(lang):
            raise SystemExit(f"invalid language: {lang}")
        path = os.path.join(comaps_dir, "iphone", "Maps", "LocalizedStrings", f"{lang}.lproj", "LocalizableTypes.strings")
        if not os.path.isfile(path):
            log(f"WARNING {path} is missing; {lang} is skipped")
            continue
        with open(path, encoding="utf-8") as f:
            tables[lang] = parse(f.read())
    return tables


def main(argv=None):
    ap = argparse.ArgumentParser(description=__doc__.split("\n")[0])
    ap.add_argument("--langs", default="en,es")
    ap.add_argument("--comaps", default=os.path.join(ROOT, "third_party", "comaps"))
    ap.add_argument("-o", "--output", default=os.path.join(ROOT, "native-comaps", "src", "main", "cpp", "generated",
                                                           "um_localized_types.inc"))
    a = ap.parse_args(argv)
    tables = load(a.comaps, [l for l in a.langs.split(",") if l], log=lambda m: print(m, file=sys.stderr))
    if "en" not in tables:
        raise SystemExit("English is required (it is the fallback)")
    os.makedirs(os.path.dirname(a.output), exist_ok=True)
    with open(a.output, "w", encoding="utf-8") as f:
        f.write(render(tables))
    print(", ".join(f"{l}: {len(t)}" for l, t in sorted(tables.items())), file=sys.stderr)


if __name__ == "__main__":
    main()
