// Minimal Android Platform for the CoMaps core, with no JNI to Java and NO NETWORK:
// all network traffic is done by Kotlin through NetworkPolicy (core-net). Here the
// CoMaps HTTP clients always fail, and the native network policy returns "no".
#include "um_platform.hpp"

#include "platform/http_client.hpp"
#include "platform/locale.hpp"
#include "platform/localization.hpp"
#include "platform/localized_types_map.cpp"  // generated by scripts/comaps-prepare.sh
#include "platform/http_thread_callback.hpp"
#include "platform/network_policy.hpp"
#include "platform/platform.hpp"
#include "platform/secure_storage.hpp"
#include "platform/settings.hpp"

#include "i18n/localisation.hpp"

#include "base/thread_pool_delayed.hpp"

#include <algorithm>
#include <map>
#include <memory>
#include <mutex>
#include <string>
#include <vector>

namespace
{
// Feature type names per language, generated by scripts/gen-localized-types.py (comaps-prepare.sh runs it). Without the
// generated file the core keeps CoMaps' English-only table.
#if __has_include("generated/um_localized_types.inc")
std::map<std::string, std::map<std::string, std::string>> const g_umTypes =
#include "generated/um_localized_types.inc"
    ;
#else
std::map<std::string, std::map<std::string, std::string>> const g_umTypes;
#endif

std::mutex g_placeMu;
std::string g_placeLang = "en";
bool g_placeApplied = false;
bool g_placeLocal = false;
}  // namespace

namespace
{
class UmPlatform : public Platform
{
public:
  void Init(std::string const & apk, std::string const & writable, std::string const & tmp)
  {
    auto withSlash = [](std::string s)
    {
      if (!s.empty() && s.back() != '/')
        s += '/';
      return s;
    };
    m_resourcesDir = apk;  // ZipFileReader reads "assets/<file>" from the APK
    m_writableDir = withSlash(writable);
    m_settingsDir = m_writableDir;
    m_tmpDir = withSlash(tmp);
    m_isTablet = false;
    SetGuiThread(std::make_unique<base::DelayedThreadPool>());
  }
};

UmPlatform & Instance()
{
  static UmPlatform platform;
  return platform;
}
}  // namespace

namespace um
{
void InitAndroidPlatform(std::string const & apk, std::string const & writable, std::string const & tmp)
{
  static std::once_flag once;
  std::call_once(once,
                 [&]
  {
    Instance().Init(apk, writable, tmp);
    // Creates the File/Network/Background threads; lives until the end of the process.
    static Platform::ThreadRunner runner;
  });
}

PlaceLocale ParsePlaceLocale(std::string const & spec)
{
  PlaceLocale p;
  auto const semi = spec.find(';');
  p.lang = spec.substr(0, semi);
  if (p.lang.empty())
    p.lang = "en";
  p.local = semi != std::string::npos && spec.compare(semi + 1, std::string::npos, "local") == 0;
  return p;
}

void ApplyPlaceLocale(PlaceLocale const & p)
{
  std::lock_guard<std::mutex> lock(g_placeMu);
  if (g_placeApplied && p.lang == g_placeLang && p.local == g_placeLocal)
    return;
  g_placeLang = p.lang;
  g_placeLocal = p.local;
  g_placeApplied = true;
  // CoMaps reads these two settings on every name lookup (feature names and the region part of the address):
  //  * map language "default" = the name as written locally comes first (then the regional languages, then the user's);
  //    empty = the user's language (GetAndroidSystemLanguages below) comes first.
  //  * alternatives "false" (SystemOrder) keeps the fallbacks to the other languages.
  settings::Set(localisation::kMapLanguageSetting, std::string(p.local ? "default" : ""));
  settings::Set(localisation::kAlternativeMapLanguageHandlingSetting, std::string("false"));
}

std::string PlaceLanguage()
{
  std::lock_guard<std::mutex> lock(g_placeMu);
  return g_placeLang;
}
}  // namespace um

Platform & GetPlatform()
{
  return Instance();
}

std::string Platform::GetMemoryInfo() const
{
  return {};
}

std::string Platform::DeviceName() const
{
  return "android";
}

std::string Platform::DeviceModel() const
{
  return "android";
}

std::string Platform::Version() const
{
  return "ultimatemaps";
}

int32_t Platform::IntVersion() const
{
  return 0;
}

Platform::EConnectionType Platform::ConnectionStatus()
{
  return EConnectionType::CONNECTION_NONE;
}

Platform::ChargingStatus Platform::GetChargingStatus()
{
  return ChargingStatus::Unknown;
}

uint8_t Platform::GetBatteryLevel()
{
  return 100;
}

namespace platform
{
NetworkPolicy GetCurrentNetworkPolicy()
{
  return NetworkPolicy(false);
}

void SecureStorage::Save(std::string const &, std::string const &) {}
bool SecureStorage::Load(std::string const &, std::string &)
{
  return false;
}
void SecureStorage::Remove(std::string const &) {}

bool HttpClient::RunHttpRequest()
{
  return false;  // no native network
}
}  // namespace platform

class HttpThread
{};

namespace downloader
{
HttpThread * CreateNativeHttpThread(std::string const &, IHttpThreadCallback &, int64_t, int64_t, int64_t,
                                    std::string const &)
{
  return nullptr;
}

void DeleteNativeHttpThread(HttpThread * thread)
{
  delete thread;
}
}  // namespace downloader

// base/thread.cpp asks for these two hooks on Android to attach threads to the JVM. Here no native
// thread calls Java, so they do nothing.
void AndroidThreadAttachToJVM() {}
void AndroidThreadDetachFromJVM() {}

// platform/preferred_languages.cpp: system languages. Kotlin decides the language (locale parameter).
std::vector<std::string> GetAndroidSystemLanguages()
{
  return {um::PlaceLanguage()};
}

namespace platform
{
Locale GetCurrentLocale()
{
  return {"en", "", "", ".", ","};
}

bool GetLocale(std::string, Locale &)
{
  return false;
}

// Human-readable type names: English table generated from CoMaps (the UI translates with its resources).
std::string GetLocalizedTypeName(std::string const & type)
{
  auto key = "type." + type;
  std::replace(key.begin(), key.end(), '-', '.');
  std::replace(key.begin(), key.end(), ':', '_');
  // The user's language first, then English (CoMaps' own table), then the raw type name.
  auto const table = g_umTypes.find(um::PlaceLanguage());
  if (table != g_umTypes.end())
  {
    auto const hit = table->second.find(key);
    if (hit != table->second.end() && !hit->second.empty())
      return hit->second;
  }
  auto const it = g_type2localizedType.find(key);
  std::string name = (it != g_type2localizedType.end()) ? it->second : std::string();
  return name.empty() ? type : name;
}

std::string GetLocalizedBrandName(std::string const & brand)
{
  return brand;
}

std::string GetLocalizedString(std::string const & key)
{
  return key;
}
}  // namespace platform
