package com.qtekfun.ultimatemaps.settings

import androidx.compose.foundation.layout.Spacer
import androidx.compose.foundation.layout.height
import androidx.compose.foundation.text.BasicText
import androidx.compose.runtime.Composable
import androidx.compose.runtime.collectAsState
import androidx.compose.runtime.getValue
import androidx.compose.ui.Modifier
import androidx.compose.ui.platform.testTag
import androidx.compose.ui.res.stringResource
import androidx.compose.ui.unit.dp
import com.qtekfun.ultimatemaps.R
import com.qtekfun.ultimatemaps.core.bikeshare.BikeShareDataManager
import com.qtekfun.ultimatemaps.core.bikeshare.BikeShareSettingsStore
import com.qtekfun.ultimatemaps.core.bikeshare.BikeShareTrigger
import com.qtekfun.ultimatemaps.core.bikeshare.BikeShareUpdateState
import com.qtekfun.ultimatemaps.core.cameras.CameraAttribution
import com.qtekfun.ultimatemaps.ui.theme.Mapas
import java.util.Locale

/** What the "Bike-share stations" group of the Navigation category reads and changes. */
class BikeShareSettingsEnv(
    val store: BikeShareSettingsStore,
    val data: BikeShareDataManager,
    val locale: () -> Locale = Locale::getDefault,
)

/**
 * Group "Bike-share stations": one switch (off by default; turning it on fetches the small station file from the catalog's
 * data server, nothing else), then a SECOND switch for live availability (off by default, says which third-party hosts it
 * contacts), the data date and count, "Update now" and the attribution of each system. The options only appear while the
 * first switch is on.
 */
@Composable
fun BikeShareSection(env: BikeShareSettingsEnv) {
    val s by env.store.settings.collectAsState()
    Spacer(Modifier.height(10.dp))
    SectionTitle(stringResource(R.string.bike_group_title))
    Card("bike_enable_card") {
        SwitchRow(stringResource(R.string.bike_switch_title), stringResource(R.string.bike_switch_body), s.enabled, "bike_switch") { on ->
            env.store.update { it.copy(enabled = on) }
            if (on) env.data.refreshAsync(BikeShareTrigger.ENABLED)
        }
    }
    if (!s.enabled) return

    Spacer(Modifier.height(10.dp))
    Card("bike_live_card") {
        SwitchRow(stringResource(R.string.bike_live_title), stringResource(R.string.bike_live_body), s.liveAvailability, "bike_live_switch") { on ->
            env.store.update { it.copy(liveAvailability = on) }
        }
    }
    Spacer(Modifier.height(10.dp))
    DataCard(env)
}

@Composable
private fun DataCard(env: BikeShareSettingsEnv) {
    val locale = env.locale()
    val generated by env.data.repository.generatedMillis.collectAsState()
    val state by env.data.updateState.collectAsState()
    Card("bike_data_card") {
        BasicText(stringResource(R.string.bike_data_title), style = Mapas.typography.body.copy(color = Mapas.colors.label))
        BasicText(
            generated?.let { stringResource(R.string.bike_data_count, env.data.repository.data.stations.size, CameraAttribution.dateText(it, locale)) }
                ?: stringResource(R.string.bike_data_never),
            style = Mapas.typography.callout.copy(color = Mapas.colors.secondaryLabel), modifier = Modifier.testTag("bike_data_count"),
        )
        BasicText(
            stringResource(R.string.bike_attribution_settings),
            style = Mapas.typography.callout.copy(color = Mapas.colors.secondaryLabel), modifier = Modifier.testTag("bike_attribution"),
        )
        val running = state is BikeShareUpdateState.Running
        TextButton(stringResource(R.string.cam_update_now), "bike_update_now", enabled = !running) { env.data.refreshAsync(BikeShareTrigger.USER) }
        if (running) BasicText(stringResource(R.string.cam_update_running), style = Mapas.typography.callout.copy(color = Mapas.colors.secondaryLabel))
        val finished = state as? BikeShareUpdateState.Finished
        if (!running && finished?.failure != null) {
            BasicText(
                stringResource(R.string.cam_update_error, stringResource(failureText(finished.failure!!))),
                style = Mapas.typography.callout.copy(color = Mapas.colors.warning), modifier = Modifier.testTag("bike_error"),
            )
        } else if (!running && finished != null) {
            BasicText(stringResource(R.string.cam_update_ok), style = Mapas.typography.callout.copy(color = Mapas.colors.secondaryLabel), modifier = Modifier.testTag("bike_result_ok"))
        }
    }
}
