package com.qtekfun.ultimatemaps.settings

import androidx.compose.foundation.layout.Spacer
import androidx.compose.foundation.layout.height
import androidx.compose.foundation.text.BasicText
import androidx.compose.runtime.Composable
import androidx.compose.runtime.collectAsState
import androidx.compose.runtime.getValue
import androidx.compose.ui.Modifier
import androidx.compose.ui.platform.testTag
import androidx.compose.ui.res.stringResource
import androidx.compose.ui.unit.dp
import com.qtekfun.ultimatemaps.R
import com.qtekfun.ultimatemaps.core.cameras.CameraAttribution
import com.qtekfun.ultimatemaps.core.chargers.ChargerDataManager
import com.qtekfun.ultimatemaps.core.chargers.ChargerSettingsStore
import com.qtekfun.ultimatemaps.core.chargers.ChargerTrigger
import com.qtekfun.ultimatemaps.core.chargers.ChargerUpdateState
import com.qtekfun.ultimatemaps.core.chargers.MinPower
import com.qtekfun.ultimatemaps.core.chargers.SocketType
import com.qtekfun.ultimatemaps.ui.theme.Mapas
import java.util.Locale

/** What the "Electric chargers" group of the Fuel stations category reads and changes. */
class ChargersSettingsEnv(
    val store: ChargerSettingsStore,
    val data: ChargerDataManager,
    val locale: () -> Locale = Locale::getDefault,
)

@androidx.annotation.StringRes
internal fun socketLabel(t: SocketType): Int = when (t) {
    SocketType.TYPE2 -> R.string.ev_socket_type2
    SocketType.CCS -> R.string.ev_socket_ccs
    SocketType.CHADEMO -> R.string.ev_socket_chademo
    SocketType.SCHUKO -> R.string.ev_socket_schuko
    SocketType.TYPE1 -> R.string.ev_socket_type1
    SocketType.TESLA -> R.string.ev_socket_tesla
    SocketType.OTHER -> R.string.ev_socket_other
}

/**
 * Group "Electric chargers": one switch (off by default; turning it on fetches the small charger file from the catalog's
 * data server, nothing else), then the plug types and the minimum power, the data date and count, "Update now" and the
 * OpenStreetMap attribution. The filters only appear while the switch is on.
 */
@Composable
fun ChargersSection(env: ChargersSettingsEnv) {
    val s by env.store.settings.collectAsState()
    SectionTitle(stringResource(R.string.ev_group_title))
    Card("ev_enable_card") {
        SwitchRow(
            stringResource(R.string.ev_switch_title), stringResource(R.string.ev_switch_body), s.enabled, "ev_switch",
        ) { on ->
            env.store.update { it.copy(enabled = on) }
            if (on) env.data.refreshAsync(ChargerTrigger.ENABLED)
        }
    }
    if (!s.enabled) return

    Spacer(Modifier.height(10.dp))
    Card("ev_sockets_card") {
        BasicText(stringResource(R.string.ev_sockets_title), style = Mapas.typography.body.copy(color = Mapas.colors.label))
        BasicText(stringResource(R.string.ev_sockets_body), style = Mapas.typography.callout.copy(color = Mapas.colors.secondaryLabel))
        SocketType.entries.filter { it in SocketType.FILTERABLE }.forEach { t ->
            ChoiceRow(stringResource(socketLabel(t)), t in s.sockets, radio = false, tag = "ev_socket_${t.name.lowercase()}") { checked ->
                env.store.update { cur -> cur.copy(sockets = if (checked) cur.sockets + t else cur.sockets - t) }
            }
        }
    }
    Spacer(Modifier.height(10.dp))
    Card("ev_power_card") {
        BasicText(stringResource(R.string.ev_power_title), style = Mapas.typography.body.copy(color = Mapas.colors.label))
        BasicText(stringResource(R.string.ev_power_body), style = Mapas.typography.callout.copy(color = Mapas.colors.secondaryLabel))
        MinPower.entries.forEach { p ->
            val label = when (p) {
                MinPower.ANY -> R.string.ev_power_any
                MinPower.KW_22 -> R.string.ev_power_22
                MinPower.KW_50 -> R.string.ev_power_50
                MinPower.KW_100 -> R.string.ev_power_100
            }
            ChoiceRow(stringResource(label), s.minPower == p, radio = true, tag = "ev_power_${p.name.lowercase()}") {
                env.store.update { cur -> cur.copy(minPower = p) }
            }
        }
    }
    Spacer(Modifier.height(10.dp))
    DataCard(env)
}

@Composable
private fun DataCard(env: ChargersSettingsEnv) {
    val locale = env.locale()
    val generated by env.data.repository.generatedMillis.collectAsState()
    val state by env.data.updateState.collectAsState()
    Card("ev_data_card") {
        BasicText(stringResource(R.string.ev_data_title), style = Mapas.typography.body.copy(color = Mapas.colors.label))
        BasicText(
            generated?.let { stringResource(R.string.ev_data_count, env.data.repository.data.chargers.size, CameraAttribution.dateText(it, locale)) }
                ?: stringResource(R.string.ev_data_never),
            style = Mapas.typography.callout.copy(color = Mapas.colors.secondaryLabel), modifier = Modifier.testTag("ev_data_count"),
        )
        BasicText(
            stringResource(R.string.ev_attribution),
            style = Mapas.typography.callout.copy(color = Mapas.colors.secondaryLabel), modifier = Modifier.testTag("ev_attribution"),
        )
        val running = state is ChargerUpdateState.Running
        TextButton(stringResource(R.string.cam_update_now), "ev_update_now", enabled = !running) { env.data.refreshAsync(ChargerTrigger.USER) }
        if (running) BasicText(stringResource(R.string.cam_update_running), style = Mapas.typography.callout.copy(color = Mapas.colors.secondaryLabel))
        val finished = state as? ChargerUpdateState.Finished
        if (!running && finished?.failure != null) {
            BasicText(
                stringResource(R.string.cam_update_error, stringResource(failureText(finished.failure!!))),
                style = Mapas.typography.callout.copy(color = Mapas.colors.warning), modifier = Modifier.testTag("ev_error"),
            )
        } else if (!running && finished != null) {
            BasicText(stringResource(R.string.cam_update_ok), style = Mapas.typography.callout.copy(color = Mapas.colors.secondaryLabel), modifier = Modifier.testTag("ev_result_ok"))
        }
    }
}
