package com.qtekfun.ultimatemaps.settings

import androidx.compose.foundation.layout.Spacer
import androidx.compose.foundation.layout.height
import androidx.compose.foundation.text.BasicText
import androidx.compose.runtime.Composable
import androidx.compose.runtime.collectAsState
import androidx.compose.runtime.getValue
import androidx.compose.ui.Modifier
import androidx.compose.ui.platform.testTag
import androidx.compose.ui.res.stringResource
import androidx.compose.ui.unit.dp
import com.qtekfun.ultimatemaps.R
import com.qtekfun.ultimatemaps.core.cameras.CameraAttribution
import com.qtekfun.ultimatemaps.core.routes.RouteDataManager
import com.qtekfun.ultimatemaps.core.routes.RouteSettingsStore
import com.qtekfun.ultimatemaps.core.routes.RouteTrigger
import com.qtekfun.ultimatemaps.core.routes.RouteUpdateState
import com.qtekfun.ultimatemaps.ui.theme.Mapas
import java.util.Locale

/** What the "Hiking and cycling routes" group of the Navigation category reads and changes. */
class TrailsSettingsEnv(
    val store: RouteSettingsStore,
    val data: RouteDataManager,
    val locale: () -> Locale = Locale::getDefault,
)

/**
 * Group "Hiking and cycling routes": one switch (off by default; turning it on fetches the route file from the catalog's data
 * server, nothing else), then which kinds are drawn, the colour legend, the data date and count, "Update now" and the
 * OpenStreetMap attribution. The rest only appears while the switch is on.
 */
@Composable
fun TrailsSection(env: TrailsSettingsEnv) {
    val s by env.store.settings.collectAsState()
    SectionTitle(stringResource(R.string.trail_group_title))
    Card("trail_enable_card") {
        SwitchRow(
            stringResource(R.string.trail_switch_title), stringResource(R.string.trail_switch_body), s.enabled, "trail_switch",
        ) { on ->
            env.store.update { it.copy(enabled = on) }
            if (on) env.data.refreshAsync(RouteTrigger.ENABLED)
        }
    }
    if (!s.enabled) return
    Spacer(Modifier.height(10.dp))
    Card("trail_kinds_card") {
        BasicText(stringResource(R.string.trail_kinds_title), style = Mapas.typography.body.copy(color = Mapas.colors.label))
        ChoiceRow(stringResource(R.string.trail_kind_hiking), s.hiking, radio = false, tag = "trail_kind_hiking") { checked ->
            env.store.update { it.copy(hiking = checked) }
        }
        ChoiceRow(stringResource(R.string.trail_kind_cycling), s.cycling, radio = false, tag = "trail_kind_cycling") { checked ->
            env.store.update { it.copy(cycling = checked) }
        }
        BasicText(
            stringResource(R.string.trail_legend),
            style = Mapas.typography.callout.copy(color = Mapas.colors.secondaryLabel), modifier = Modifier.testTag("trail_legend"),
        )
    }
    Spacer(Modifier.height(10.dp))
    DataCard(env)
}

@Composable
private fun DataCard(env: TrailsSettingsEnv) {
    val locale = env.locale()
    val generated by env.data.repository.generatedMillis.collectAsState()
    val state by env.data.updateState.collectAsState()
    Card("trail_data_card") {
        BasicText(stringResource(R.string.trail_data_title), style = Mapas.typography.body.copy(color = Mapas.colors.label))
        BasicText(
            generated?.let { stringResource(R.string.trail_data_count, env.data.repository.data.trails.size, CameraAttribution.dateText(it, locale)) }
                ?: stringResource(R.string.trail_data_never),
            style = Mapas.typography.callout.copy(color = Mapas.colors.secondaryLabel), modifier = Modifier.testTag("trail_data_count"),
        )
        BasicText(
            stringResource(R.string.trail_attribution),
            style = Mapas.typography.callout.copy(color = Mapas.colors.secondaryLabel), modifier = Modifier.testTag("trail_attribution"),
        )
        val running = state is RouteUpdateState.Running
        TextButton(stringResource(R.string.cam_update_now), "trail_update_now", enabled = !running) { env.data.refreshAsync(RouteTrigger.USER) }
        if (running) BasicText(stringResource(R.string.cam_update_running), style = Mapas.typography.callout.copy(color = Mapas.colors.secondaryLabel))
        val finished = state as? RouteUpdateState.Finished
        if (!running && finished?.failure != null) {
            BasicText(
                stringResource(R.string.cam_update_error, stringResource(failureText(finished.failure!!))),
                style = Mapas.typography.callout.copy(color = Mapas.colors.warning), modifier = Modifier.testTag("trail_error"),
            )
        } else if (!running && finished != null) {
            BasicText(stringResource(R.string.cam_update_ok), style = Mapas.typography.callout.copy(color = Mapas.colors.secondaryLabel), modifier = Modifier.testTag("trail_result_ok"))
        }
    }
}
