package com.qtekfun.ultimatemaps.settings

import androidx.compose.foundation.layout.Spacer
import androidx.compose.foundation.layout.height
import androidx.compose.foundation.text.BasicText
import androidx.compose.runtime.Composable
import androidx.compose.runtime.collectAsState
import androidx.compose.runtime.getValue
import androidx.compose.ui.Modifier
import androidx.compose.ui.platform.testTag
import androidx.compose.ui.res.stringResource
import androidx.compose.ui.unit.dp
import com.qtekfun.ultimatemaps.R
import com.qtekfun.ultimatemaps.core.cameras.AlertSoundMode
import com.qtekfun.ultimatemaps.core.cameras.CameraAttribution
import com.qtekfun.ultimatemaps.core.zbe.ZbeDataManager
import com.qtekfun.ultimatemaps.core.zbe.ZbeSettingsStore
import com.qtekfun.ultimatemaps.core.zbe.ZbeTrigger
import com.qtekfun.ultimatemaps.core.zbe.ZbeUpdateState
import com.qtekfun.ultimatemaps.ui.theme.Mapas
import java.util.Locale

/** What the "Low-emission zones" group of the Alerts category reads and changes. */
class ZbeSettingsEnv(
    val store: ZbeSettingsStore,
    val data: ZbeDataManager,
    /** Called after the switch changes, so the navigation prompt can be started. */
    val onChanged: () -> Unit = {},
    val locale: () -> Locale = Locale::getDefault,
)

/**
 * Group "Low-emission zones": one switch (off by default; turning it on fetches the small zone file from the catalog's data
 * server, nothing else), then the map toggle and how the "ahead" prompt is announced, the data date and count, "Update now",
 * the OpenStreetMap attribution and the notice that the data may be incomplete. The options only appear while the switch is on.
 */
@Composable
fun ZbeSection(env: ZbeSettingsEnv) {
    val s by env.store.settings.collectAsState()
    Spacer(Modifier.height(10.dp))
    SectionTitle(stringResource(R.string.zbe_group_title))
    Card("zbe_enable_card") {
        SwitchRow(stringResource(R.string.zbe_switch_title), stringResource(R.string.zbe_switch_body), s.enabled, "zbe_switch") { on ->
            env.store.update { it.copy(enabled = on) }
            if (on) env.data.refreshAsync(ZbeTrigger.ENABLED)
            env.onChanged()
        }
    }
    if (!s.enabled) return

    Spacer(Modifier.height(10.dp))
    Card("zbe_map_card") {
        SwitchRow(stringResource(R.string.zbe_map_title), stringResource(R.string.zbe_map_body), s.showOnMap, "zbe_map_switch") { on ->
            env.store.update { it.copy(showOnMap = on) }
        }
    }
    Spacer(Modifier.height(10.dp))
    Card("zbe_prompt_card") {
        BasicText(stringResource(R.string.zbe_prompt_title), style = Mapas.typography.body.copy(color = Mapas.colors.label))
        AlertSoundMode.entries.forEach { m ->
            val label = when (m) {
                AlertSoundMode.SOUND -> R.string.alert_mode_sound
                AlertSoundMode.VOICE -> R.string.alert_mode_voice
                AlertSoundMode.SILENT -> R.string.alert_mode_silent
            }
            ChoiceRow(stringResource(label), s.promptMode == m, radio = true, tag = "zbe_prompt_${m.name.lowercase()}") {
                env.store.update { cur -> cur.copy(promptMode = m) }
            }
        }
        Spacer(Modifier.height(4.dp))
        BasicText(stringResource(R.string.alert_mode_note), style = Mapas.typography.callout.copy(color = Mapas.colors.secondaryLabel))
    }
    Spacer(Modifier.height(10.dp))
    DataCard(env)
}

@Composable
private fun DataCard(env: ZbeSettingsEnv) {
    val locale = env.locale()
    val generated by env.data.repository.generatedMillis.collectAsState()
    val state by env.data.updateState.collectAsState()
    Card("zbe_data_card") {
        BasicText(stringResource(R.string.zbe_data_title), style = Mapas.typography.body.copy(color = Mapas.colors.label))
        BasicText(
            generated?.let { stringResource(R.string.zbe_data_count, env.data.repository.data.zones.size, CameraAttribution.dateText(it, locale)) }
                ?: stringResource(R.string.zbe_data_never),
            style = Mapas.typography.callout.copy(color = Mapas.colors.secondaryLabel), modifier = Modifier.testTag("zbe_data_count"),
        )
        BasicText(
            stringResource(R.string.zbe_data_notice),
            style = Mapas.typography.callout.copy(color = Mapas.colors.secondaryLabel), modifier = Modifier.testTag("zbe_notice"),
        )
        BasicText(
            stringResource(R.string.attr_zbe_osm),
            style = Mapas.typography.callout.copy(color = Mapas.colors.secondaryLabel), modifier = Modifier.testTag("zbe_attribution"),
        )
        val running = state is ZbeUpdateState.Running
        TextButton(stringResource(R.string.cam_update_now), "zbe_update_now", enabled = !running) { env.data.refreshAsync(ZbeTrigger.USER) }
        if (running) BasicText(stringResource(R.string.cam_update_running), style = Mapas.typography.callout.copy(color = Mapas.colors.secondaryLabel))
        val finished = state as? ZbeUpdateState.Finished
        if (!running && finished?.failure != null) {
            BasicText(
                stringResource(R.string.cam_update_error, stringResource(failureText(finished.failure!!))),
                style = Mapas.typography.callout.copy(color = Mapas.colors.warning), modifier = Modifier.testTag("zbe_error"),
            )
        } else if (!running && finished != null) {
            BasicText(stringResource(R.string.cam_update_ok), style = Mapas.typography.callout.copy(color = Mapas.colors.secondaryLabel), modifier = Modifier.testTag("zbe_result_ok"))
        }
    }
}
